---
- name: Install unzip
  apt: name=unzip state=present update_cache=yes

- name: Install consul
  unarchive:
    remote_src: yes
    src: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /usr/local/bin
    creates: /usr/local/bin/consul
    mode: 0555

- name: Create consul directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /opt/consul
  - /etc/consul.d
  - /run/consul

- name: Choose agent config file for client
  set_fact:
    consul_config_file: consul_client_config.j2
  when: consul_type == "consul_client"

- name: Choose agent config file for server
  set_fact:
    consul_config_file: consul_server_config.j2
  when: consul_type == "consul_server"

- name: Generate agent config file
  template:
    src: "{{ consul_config_file }}"
    dest: /etc/consul.d/config.json

- name: Create consul user
  user: name=consul

- name: Grant ownership of folders
  file:
    path: "{{ item }}"
    owner: consul
    group: consul
  with_items:
  - /opt/consul
  - /etc/consul.d
  - /run/consul

- name: Configure consul service
  copy:
    src: consul.service
    dest: /etc/systemd/system/consul.service

- name: Generate service config file
  copy:
    src: consul_{{ instance_name }}.json
    dest: /etc/consul.d/{{ instance_name }}.json
  when: consul_type == "consul_client"

  notify:
    - restart consul

- name: ensure consul is running and enabled
  service: name=consul state=started enabled=yes


- name: Install dnsmasq for consul resolution
  apt: name=dnsmasq state=present update_cache=yes

- name: Configure dnsmasq for consul resolution
  copy:
    src: 10-consul
    dest: /etc/dnsmasq.d/10-consul

  notify:
    - restart dnsmasq

- name: ensure dnsmasq is running and enabled
  service: name=dnsmasq state=started enabled=yes
