---
- name: Install unzip
  apt: name=unzip state=present update_cache=yes

- name: Install consul
  unarchive:
    remote_src: yes
    src: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /usr/local/bin
    creates: /usr/local/bin/consul
    mode: 0555

- name: Create consul directories
  file: path=/opt/consul state=directory
  file: path=/etc/consul.d state=directory
  file: path=/run/consul state=directory

- name: Generate config file
  template:
    src: consul_client_config.j2
    dest: /etc/consul.d/config.json
