apiVersion: 1
datasources:
 - name: Prometheus
   type: prometheus
   access: proxy
   orgId: 1
   url: http://prometheus.service.consul:9090
   isDefault: true
   version: 1
editable: false
EOF

cat << EOF | sudo tee /etc/grafana/provisioning/dashboards/all.yml
apiVersion: 1

providers:
- name: 'default'
  orgId: 1
  folder: ''
  type: file
  disableDeletion: false
  updateIntervalSeconds: 10 #how often Grafana will scan for changed dashboards
  options:
    path: /var/lib/grafana/dashboards
