---
- name: Install Docker from Repo
  apt:
    name: docker.io
    update_cache: yes
    state: present

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

  notify:
    - restart docker

- name: ensure docker is running and enabled
  service: name=docker state=started enabled=yes
