---
### Deploy prometheus ###
- hosts: localhost
  become: yes
  vars:
    instance_name: prometheus
  tasks:
    - name: Gather EC2 facts
      ec2_remote_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ instance_name }}"
      register: ec2_facts

    - name: Get private IP
      debug:
        msg: "{{ ec2_facts.instances[0].private_ip_address }}"
      register: priv_ip

- hosts: tag_Name_prometheus
  become: yes
  vars:
    instance_name: prometheus
    priv_ip: "{{ hostvars.localhost.priv_ip['msg'] }}"
    consul_type: consul_client

  roles:
    - prometheus
    - consul


### Deploy consul servers ###
### consul-server1 ###
- hosts: localhost
  become: yes
  vars:
    instance_name: consul-server1
  tasks:
    - name: Gather EC2 facts
      ec2_remote_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ instance_name }}"
      register: ec2_facts

    - name: Get private IP
      debug:
        msg: "{{ ec2_facts.instances[0].private_ip_address }}"
      register: priv_ip

- hosts: tag_Name_consul-server1
  become: yes
  vars:
    instance_name: consul-server1
    priv_ip: "{{ hostvars.localhost.priv_ip['msg'] }}"
    consul_type: consul_server

  roles:
    - consul


### consul-server2 ###
- hosts: localhost
  become: yes
  vars:
    instance_name: consul-server2
  tasks:
    - name: Gather EC2 facts
      ec2_remote_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ instance_name }}"
      register: ec2_facts

    - name: Get private IP
      debug:
        msg: "{{ ec2_facts.instances[0].private_ip_address }}"
      register: priv_ip

- hosts: tag_Name_consul-server2
  become: yes
  vars:
    instance_name: consul-server2
    priv_ip: "{{ hostvars.localhost.priv_ip['msg'] }}"
    consul_type: consul_server

  roles:
    - consul


### consul-server3 ###
- hosts: localhost
  become: yes
  vars:
    instance_name: consul-server3
  tasks:
    - name: Gather EC2 facts
      ec2_remote_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ instance_name }}"
      register: ec2_facts

    - name: Get private IP
      debug:
        msg: "{{ ec2_facts.instances[0].private_ip_address }}"
      register: priv_ip

- hosts: tag_Name_consul-server3
  become: yes
  vars:
    instance_name: consul-server3
    priv_ip: "{{ hostvars.localhost.priv_ip['msg'] }}"
    consul_type: consul_server

  roles:
    - consul

