---
- hosts: localhost
  become: yes
  vars:
    instance_name: prometheus
  tasks:
    - name: Gather EC2 facts
      ec2_remote_facts:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ instance_name }}"
      register: ec2_facts

    - name: Get private IP
      debug:
        msg: "{{ ec2_facts.instances[0].private_ip_address }}"
      register: priv_ip

- hosts: tag_Name_prometheus
  become: yes
  vars:
    instance_name: prometheus
    priv_ip: "{{ hostvars.localhost.priv_ip }}"

  roles:
    - prometheus
    - consul
