---
### consul1 ###
- hosts: localhost
  vars:
    instance_name: consul1
  tasks:
    - include: get_priv_ip.yml

- hosts: "tag_Name_{{ instance_name }}"
  vars:
    instance_name: consul1
    consul_type: consul_server

  roles:
    - consul


### consul2 ###
- hosts: localhost
  vars:
    instance_name: consul2
  tasks:
    - include: get_priv_ip.yml

- hosts: "tag_Name_{{ instance_name }}"
  vars:
    instance_name: consul2
    consul_type: consul_server

  roles:
    - consul


### consul3 ###
- hosts: localhost
  vars:
    instance_name: consul3
  tasks:
    - include: get_priv_ip.yml

- hosts: "tag_Name_{{ instance_name }}"
  vars:
    instance_name: consul3
    consul_type: consul_server

  roles:
    - consul


### prometheus ###
- hosts: localhost
  vars:
    instance_name: prometheus
  tasks:
    - include: get_priv_ip.yml

- hosts: "tag_Name_{{ instance_name }}"
  vars:
    instance_name: prometheus
    consul_type: consul_client

  roles:
    - prometheus
    - consul


### grafana ###
- hosts: localhost
  vars:
    instance_name: grafana
  tasks:
    - include: get_priv_ip.yml

- hosts: "tag_Name_{{ instance_name }}"
  vars:
    instance_name: grafana
    consul_type: consul_client

  roles:
    - grafana
    - consul


### elk ###
- hosts: localhost
  vars:
    instance_name: elk
  tasks:
    - include: get_priv_ip.yml

- hosts: "tag_Name_{{ instance_name }}"
  vars:
    instance_name: elk
    consul_type: consul_client

  roles:
    - elk
    - consul


