---
- hosts: prometheus
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Install prometheus package
    apt: name=prometheus state=present update_cache=yes
  - name: Create a temp dir for git clone
    file:
      path: /home/ubuntu/temp
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: 0700
  - name: Clone from git
    git:
      repo: https://github.com/sharonnavon/project.git
      dest: /home/ubuntu/temp
    become: no
  - name: Copy prometheus.yml from git clone
    copy:
      remote_src: true
      src: /home/ubuntu/temp/files/prometheus.yml
      dest: /etc/prometheus/prometheus.yml
      force: yes
  - name: Copy hosts file from git clone
    copy:
      remote_src: true
      src: /home/ubuntu/temp/files/hosts
      dest: /etc/hosts
      force: yes
  - name: Delete the temp dir
    file: path=/home/ubuntu/temp state=absent
    notify:
      - restart prometheus service
  handlers:
    - name: restart prometheus service
      service: name=prometheus state=restarted

- hosts: grafana
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Download grafana package
    get_url:
      url: https://dl.grafana.com/oss/release/grafana_5.4.2_amd64.deb
      dest: /home/ubuntu/grafana_5.4.2_amd64.deb
  - name: Install grafana package
    apt:
      deb: /home/ubuntu/grafana_5.4.2_amd64.deb
  - name: Initiate admin user
    replace:
      path: /etc/grafana/grafana.ini
      regexp: ';admin_user = admin'
      replace: 'admin_user = admin'
  - name: Initiate admin password
    replace:
      path: /etc/grafana/grafana.ini
      regexp: ';admin_password = admin'
      replace: 'admin_password = admin'
    notify:
      - restart grafana service
  handlers:
    - name: restart grafana service
      service: name=grafana-server state=restarted

- hosts: node-exporter
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Create a temp dir for git clone
    file:
      path: /home/ubuntu/temp
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: 0700
  - name: Clone from git
    git:
      repo: https://github.com/ops-school/session-monitoring.git
      dest: /home/ubuntu/temp
    become: no
  - name: Run my_dummy_exporter.py
    shell: nohup python /home/ubuntu/temp/training_session/my_dummy_exporter.py &
       